### ISSUE TITLE
smartImageCache v1.0.2 feedback

### ISSUE THREAD

**Issue by JesseHC** [FilippoBoscarino/smartImageCache-for-Zenphoto#4]
I noticed some small issues.

If running it in chunks, if an image fails, the page will stop. This is nice so you can see what failed, but it would be even better if there was an option for it to automatically try again if an image fails. Maybe even have an option for attempts?

As it is right now, if there is a large gallery and you are forced to process it in small chunks, you have to be constantly monitoring it for failures.

The Reload chunk button at the top is not working for me when there is a failed image. I have to use the Reload chunk button next to the chunk at the bottom of the page, at least in Firefox 111.0.1. I then get this popup and it works after:

> To display this page, Firefox must send information that will repeat any action (such as a search or order confirmation) that was performed earlier.
> Cancel Resend

It would be nice if all the albums already processed were either not shown, collapsed, or have the chunk being processed on top of all of them on the page. Right now on a large gallery there can be a long page of repeated entries saying:

> 
> Album 82 - Example 6 Items
>         
> This album does not have any images.

By the time you scroll to the bottom, the page can refresh and send you back to the top before you’ve even gotten a chance to view the images being processed. Especially if they have already been cached. It is a little frustrating.

Confused why it is not caching multimedia objects, when they can have sidecar images that often need to be cached?

This might be an issue with cacheManager, but your extension is highlighting it.

On mine:
> _Multimedia: 1071 sizes not required_

And on the specific items: _“Multimedia object. No cache needed”_

When, in fact, almost all of them had sidecar images that needed to be cached.

Maybe shrink the plugin icon to match the other icons at 16x16.

**Language issues that can be fixed:**

For the options, under:

> How many items per cycle
>  _“Value 0 (zero) means all images togheter in one chunk.”_

change to **together**

> _How long does process lasts_

to **last**

> _NOTE: Defining too long periods can create problems to server availability.
> Do not set periods higherer than 10 secs._

NOTE: Defining too long **of** periods can create problems to server availability.
Do not set periods **higher** than 10 **seconds**.

> _NOTE: If not stopped within this period of secs, process proceed on next page.
> If some sized image production goes wrong, process try to stop by itself._

NOTE: If not stopped within this period of **seconds**, process **proceeds** on **the** next page.
If some sized image production goes wrong, process **tries** to stop by itself.

**On the Cache images page-**

> _How many items has to be processed every cicle. Value 0 (zero) means all images togheter in one chunk. It can be used to review and control all the sizes toghether, when they are already cached._

How many items has to be processed every **cycle**. Value 0 (zero) means all images **together** in one chunk. It can be used to review and control all the sizes **together**, when they are already cached.

The following are both problems with regular cacheManager, so just noting they still exist.

Trying default chunks of 20, it errors out on my live server when using cURL:

> Content Encoding Error
> 
> An error occurred during a connection to -.com.
> 
>     Please contact the website owners to inform them of this problem.
> 

If using classic, it appears to be done rather quickly, but the page will lock up and many of the thumbs will not actually load.

Thanks again for doing this. The ability to limit cacheManager to manageable chunks is a big improvement for limited servers.

**Comment by acrylian** [comment]
> Maybe shrink the plugin icon to match the other icons at 16x16.

In 1.6.1 we will force by fake resizing custom icons.

> By the time you scroll to the bottom, the page can refresh and send you back to the top before you’ve even gotten a chance to view the images being processed. Especially if they have already been cached. It is a little frustrating.

A reason why it originally display all on one page. If possible a simple way might be to log failures in the debuglog if possible.

> Confused why it is not caching multimedia objects, when they can have sidecar images that often need to be cached?
> This might be an issue with cacheManager, but your extension is highlighting it.

Yes, as noted on the other ticket it is an issue of the cacheManager not covering these as well. I will look into that for the main cacheManager.

**Comment by FilippoBoscarino** [comment]
> I will look into that for the main cacheManager.

I will wait for some info about it, so I will move accordly

**Comment by acrylian** [comment]
> Yes, as noted on the other ticket it is an issue of the cacheManager not covering these as well. I will look into that for the main cacheManager.

The 1.6.1a cacheManager now covers sidecar images, too. There have been a few other small changes that should be self explaining I think.

**Comment by FilippoBoscarino** [comment]
Hi JesseHC,
many thanks for your review.
here some feedback

> it would be even better if there was an option for it to automatically try again if an image fails. Maybe even have an option for attempts

I am thinking about something similar, maybe just a button in page, to be upgraded to something automatic when tested enough in functionality

> if there is a large gallery and you are forced to process it in small chunks, you have to be constantly monitoring it for failures

I was a bit doubtfull in introducing this stop, and surely is a temporary solution.
The basic approach I had in thinking this plugin was: let leave it work on the whole tree automatically by itself and, at the end, browse it again with 0 option to see and verify what happened, when everything cached.
At the very beginning I thought to introduce some sort of verifying page, then I discovered that it was implicit in the process itself.
So this stop could be not only unuseful but maybe it could bother.
Unfortunately (at least in my environment) basing on the fail report is not reliable, because there could be some images appearing as generated but unreadable or corrupted, once displayed.
I think that the final solution is a bit too far yet, and maybe only usage can suggest it.
Anyway it is in my awareness

> The Reload chunk button at the top is not working for me

I will check

> It would be nice if all the albums already processed were either not shown, collapsed, or have the chunk being processed on top of all of them on the page

There is a limitation right now due to the fact that images to be processed are identified by browsing the albums tree by the beginning, in every chunk (as cacheManager did).
I am thinkink to engineer a new version, browsing them from db, that could be much more effective and fast.
On the other end, my very first release was built with the "detail" HTML tag, just for this purpose.
But then I removed even "ul" and other structures, to avoid that browser have to wait for the end of the structure, before rendering the page.
Solution can only raise up from db approach, in my opinion.

> By the time you scroll to the bottom, the page can refresh

For this moment, I suggest a short timing (like 3secs) for automatic launch and a more relaxed (like 20secs or even manual) timing in the review launch.
This is how I am using it right now.

> Confused why it is not caching multimedia objects

This was directly inherited by cacheManager.
But I have planned to investigate if I can introduce a new method to manage sidecars

> Maybe shrink the plugin icon to match the other icons at 16x16
I will

> Language issues that can be fixed
Many thanks, I will correct them

> The following are both problems with regular cacheManager

I have read somewhere that problems about cURL usage are diffused for the whole Zenphoto platform, on some environments.
I definitevely did not extend my development in approaching such issue.

> If using classic, it appears to be done rather quickly, but the page will lock up and many of the thumbs will not actually load

This is a part of the problem I was talking about earlier, when saying that basing only on fails it is not reliable.

Thanks for your support

**Comment by FilippoBoscarino** [comment]
> The 1.6.1a cacheManager now covers sidecar images, too

I am waiting for the 1.6.1 release so much... ;-)

**Comment by acrylian** [comment]
Btw, let me know if you like your plugin to get an extensions entry on our site and be announced generally.

**Comment by FilippoBoscarino** [comment]
I would be very glad, but I think is better to wait for next release that could be more robust
